### ISSUE TITLE
3 issues found - User, Archive, Report

### ISSUE THREAD

**Issue by PaulyJ1** [ArneVanDaele/dvz_shoutbox_pvt#1]
**1. User/Avatar**
* 1a. Hovering over avatar provides the wrong profile link for myBB.

![user](https://cloud.githubusercontent.com/assets/12805807/9702254/4abe155e-544d-11e5-8e6a-e49dcd4708ca.png)

* 1b. This then sends you to a 404 error page. [Link should be along the lines of http://SITENAME.com/member.php?action=profile&uid=UID]

![404](https://cloud.githubusercontent.com/assets/12805807/9702251/4aa0e416-544d-11e5-90b6-d63647f94870.png)

**2. Archive**
* 2a. Archive falls outside of the bar or has been somewhat misplaced.

![archive](https://cloud.githubusercontent.com/assets/12805807/9702253/4abbeb9e-544d-11e5-9db4-f45853ed8f43.png)

**3, Report**
* 3a. Report button/feature is shown in Dutch on English version.

![report](https://cloud.githubusercontent.com/assets/12805807/9702252/4ab58448-544d-11e5-9217-96602c0e840e.png)

**Comment by ArneVanDaele** [comment]
This issue will be fixed today.

**Comment by PaulyJ1** [comment]
Thanks! :)

**Comment by PaulyJ1** [comment]
Have all issues been resolved? Or just the Report button?

**Comment by noxwyll** [comment]
this is fixed in the pullrequests that just got merged in.
